### ISSUE TITLE
I'm not sure how to use it ?

### ISSUE THREAD

**Issue by AirMarty** [remorses/docker-phobia#4]
Hi, 
thank you for your work !

I would like to test it but not sure of how to use it, I try this : 
```
$ docker-phobia
✔ nginx:latest
internal server listening on http://localhost:35591
```

And nothing happen, just to be sure I opened indicated port and just get : 
`{"version":"1.0.0","name":"docker-phobia"}`

May be its too early to test it or i'm doing something wrong ?

Thank you !

**Comment by remorses** [comment]
It should open the browser with the treemap, maybe you are in an ssh environment? I will change the code to print the url to open in case the terminal can't open the browser

**Comment by AirMarty** [comment]
You're right i'm using lot of hosts on my intranet, I assume there's path in the URL to open to access result ; you can also print  it either with host name or host IP wich can be usefull for instance something like that :
"Your browser will automaticly open the service or navigate to http://**my-host-ip**:**port****/path-to-the-phoebia-result** ".
Lot of project mainly focus on localhost (IDK why) ; may be due to the lack of real use cases.

**Comment by remorses** [comment]
i added the url in the terminal output, another possible feature to add would be to create a tunnel using Cloudflare so you can inspect images in remote machines. PRs for this welcome

**Comment by AirMarty** [comment]
Hi, i'm not sure what i have to do, may I test something, did you released version to test-it ?

Thanx

**Comment by remorses** [comment]
you can install with `go install github.com/remorses/docker-phobia@latest`

**Comment by AirMarty** [comment]
ok i tested-it and its ok I can access the URL shown ^^

Thanx
